version: '3.7'

services:

  playground:
    container_name: playground
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5002:80'