name: Partners App Deployment

on: workflow_dispatch

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/.scripts
            ./docker-deploy.sh